version: "3.6"

services:

  # Backend Django
  backend:
    user: 1000:1000
    build: ./backend
    volumes:
      # Directory of static files of Django
      - ./archive/django_static:/app/django_static
      # Directory of Logs 
      - ./log:/log
      # Source codes, only used in development.
      - ./backend:/app
    env_file:
      - .env
    # depends_on:
    #   - database


  # Web Server Nginx 
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      # Nginx configuration file
      - ./nginx/development.conf:/etc/nginx/conf.d/default.conf:ro

      # Directory of static files of Django
      - ./archive/django_static:/var/www/django_static
    depends_on:
      - backend
